# -*- coding: utf-8 -*-
"""Script Ingest Log (Cập nhật IP)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4RDErt1N0PYEWwIZfBXoaCcjDg5Q8nb
"""

import csv
import time
import os
import random

# 1. CẤU HÌNH
csv_file = 'cic_200_samples.csv'
log_dir = "C:\\Logs"
log_file = os.path.join(log_dir, "cic_ids_sim.log")

# Danh sách IP giả lập kẻ tấn công (để đa dạng hóa dữ liệu cho AbuseIPDB/AI)
ATTACKER_IPS = [
    "185.119.253.133",
    "180.184.134.158",
    "35.222.117.243",
    "179.33.186.151",
    "159.65.143.148",
    "80.94.92.187",
    "62.60.131.157",
    "179.43.184.242",
    "164.92.217.245",
    "253.22.126.216"
]
VICTIM_IP_MOCK = "192.168.38.130"
SAFE_IP_MOCK = "1.1.1.1"

def run_ingestion():
    if not os.path.exists(log_dir): os.makedirs(log_dir)

    print(f"[*] Bat dau day du lieu vao {log_file}...")
    try:
        with open(csv_file, mode='r') as f:
            reader = csv.DictReader(f)
            count = 0
            with open(log_file, "a") as log:
                for row in reader:
                    # Xử lý Label (xóa khoảng trắng thừa)
                    label = row.get(' Label', row.get('Label', 'BENIGN')).strip()
                    dst_port = row.get(' Destination Port', row.get('Destination Port', '0'))

                    # Gán IP giả lập dựa trên nhãn dữ liệu
                    if label != "BENIGN":
                        # Chọn ngẫu nhiên 1 IP từ danh sách kẻ tấn công đã set sẵn
                        src_ip = random.choice(ATTACKER_IPS)
                        dst_ip = VICTIM_IP_MOCK
                    else:
                        src_ip = SAFE_IP_MOCK
                        dst_ip = VICTIM_IP_MOCK

                    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
                    # Format log chuẩn Key=Value để Splunk tự tách field
                    log_entry = f"{timestamp} | EVENT=CIC_IDS_SIM | SRC_IP={src_ip} | DST_IP={dst_ip} | DST_PORT={dst_port} | ATTACK_TYPE={label}\n"

                    log.write(log_entry)
                    log.flush()
                    count += 1
                    if count % 50 == 0: print(f"[+] Da day {count} mau...")
                    time.sleep(1) # Delay để n8n/AI xử lý kịp

        print(f"\n[SUCCESS] Hoan tat {count} mau. SRC_IP/DST_IP da duoc mo phong ngau nhien cho SOC flow.")
    except Exception as e:
        print(f"[ERROR] Loi: {e}")

if __name__ == "__main__":
    run_ingestion()